#!/bin/bash

SCRIPT_FOLDER="$HOME/bin"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
    vim $SCRIPT_FILE
    echo Script $1 already exist, opening file
else 
    echo '#!/bin/bash' > $SCRIPT_FILE
    chmod +x $SCRIPT_FILE
    vim $SCRIPT_FILE
    echo Script $1 created
fi
