#!/bin/bash

pkill polybar
xrandr --output DVI-D-0 --auto --output DP-5 --auto --output HDMI-0 --auto
xrandr --output HDMI-0 --pos 0x0 --output DVI-D-0 --primary --pos 1920x368 --output DP-5 --rotate normal --pos 3840x0
polybar -q DVI &
polybar -q DP &
polybar -q HDMI &

